### ISSUE TITLE
[BUG] labcreate.ts, instructor.ts errors

### ISSUE THREAD

**Issue by cemersoz** [learnlinux/tuxlab-app#138]
@DerekTBrown  meteor prints out these errors
client/imports/ui/pages/instructor/instructor.ts (25, 29): Cannot find module '../../components/loadscreen/loadscreen.ts'.
client/imports/ui/pages/lab/labcreate.ts (32, 10): Property 'lab' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (33, 10): Property 'lab' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (34, 10): Property 'lab' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (35, 10): Property 'uploaded' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (36, 10): Property 'output' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (41, 10): Property 'uploaded' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (43, 5): Cannot find name 'Collections'.
client/imports/ui/pages/lab/labcreate.ts (45, 20): Property 'name' does not exist on type 'LabCreate'.
client/imports/ui/pages/lab/labcreate.ts (48, 15): Cannot find name 'file'. Did you mean the instance member 'this.file'?
client/imports/ui/pages/lab/labcreate.ts (69, 5): Cannot find name 'file'. Did you mean the instance member 'this.file'?

**Comment by DerekTBrown** [comment]
I know... they are getting fixed.
