### ISSUE TITLE
[FEATURE] Course Settings Page

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#151]
course_dashboard for instructors:

- [x] Permissions
- [x] Course Description
- [x] Course Title
- [x] Syllabus
- [ ] Labs, Lab Due Dates, ETC

**Comment by sandershihacker** [comment]
Is this on the same course_dashboard page, or an entirely separate course_settings page in the course folder?

**Comment by DerekTBrown** [comment]
same as course_dashboard

**Comment by DerekTBrown** [comment]
I created a MDEditor component which you can use to edit the syllabus.

**Comment by sandershihacker** [comment]
Syllabus markdown and editor complete.

**Comment by sandershihacker** [comment]
Permissions portion done.

**Comment by sandershihacker** [comment]
Course Description and Course Title edit functionality complete. Style will be done when Angular 2 Material input doesn't break.
