### ISSUE TITLE
[BUG] Fix Instructor Name Schema

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#161]
We need to modify the schema for courses to have instructors saved as a tuple of name and id.  This then needs to be modified wherever we pull the instructor id and name (particularly the explore and search views).

**Comment by sandershihacker** [comment]
Already done in the Simple Schema, still need to fix in pages.

**Comment by DerekTBrown** [comment]
Yes.. in particular the explore page
