### ISSUE TITLE
[DOCS] API Examples, Documentation, Testing

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#184]

**Comment by cemersoz** [comment]
@DerekTBrown thank you for this issue. I shall cherish it

**Comment by DerekTBrown** [comment]
PR?

**Comment by DerekTBrown** [comment]
@cemersoz this needs to be redone. Its not clear.

**Comment by DerekTBrown** [comment]
- [ ] Why are Student / Env capitalized?
- [ ] RO: http://tuxlab.org/docs/#student-api
