### ISSUE TITLE
[FEATURE] LabFile Markdown Editing

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#186]
- [X] Implement a SimpleMDE Angular2 component (@DerekTBrown)
- [x] Implement a RegEx to Export LabFile after updates (@AaronMortenson)
- [x] Add an Edit Button to LabView Pages (@SanderShiHacker)
- [x] Create a Meteor Method to change / export a labfile (@cemersoz)

**Comment by cemersoz** [comment]
@DerekTBrown reopen this
@sandershihacker I have a meteor method, 'exportLab' you can call with a labId, it returns the modified lab file

This issue is all yours

**Comment by DerekTBrown** [comment]
Deprecated.
