### ISSUE TITLE
[FEATURE] Convenience Methods for Instructors

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#193]
- [ ] File Diff
- [ ] Git Clone
- [ ] Wget / Gzip

**Comment by trunkatedpig** [comment]
https://gist.github.com/trunkatedpig/26937399c44bf054a207c3e34901471b

**Comment by DerekTBrown** [comment]
1) Opts should always be last:
https://gist.github.com/trunkatedpig/26937399c44bf054a207c3e34901471b#file-functions-L47

2) You are missing the point of this issue.  The whole idea is to make wrapper functions- not just copy the string verbatim:
https://gist.github.com/trunkatedpig/26937399c44bf054a207c3e34901471b#file-functions-L53

FIX

**Comment by DerekTBrown** [comment]
This is going to have to be redone-
