### ISSUE TITLE
[REFACTOR] Cache Updates

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#195]
Some concerns we need to discuss:

1) Expiry / Renewal
We want them to expire after inactivity.  This is fairly easy to implement, we just need to do it.

2) toJSON and fromJSON Session Object
I don't believe you did these- not sure.

**Comment by cemersoz** [comment]
I didn't do 2, I will today. It should be fairly easy to implement.

**Comment by DerekTBrown** [comment]
Get fromJSON working....

**Comment by cemersoz** [comment]
see
it wercks
But I can't test whether I can use it to ssh... BECAUSE THAT DOESN'T WERCKER

**Comment by DerekTBrown** [comment]
I will then work on cache expiry and renewal

**Comment by DerekTBrown** [comment]
Deprecated.
