### ISSUE TITLE
[BUG] Collections allow errors

### ISSUE THREAD

**Issue by cemersoz** [learnlinux/tuxlab-app#207]
@sandershihacker 
@DerekTBrown 

I don't have access to update course_records if the current user is not an instructor for that course. This means I can't automatically updated attempts, grades or anything from the server side. We need server side authentication.

Also, since the collections object is only on the server side, would it not be better to check for permission where we expose the db, i.e. meteor methods?

**Comment by DerekTBrown** [comment]
1) That is not how Meteor works- you must be encountering some other error.  The Meteor allow/deny statements only apply to client side database transactions, not those which originate on the server.  Any request to the collections object you make on the server is allowed.

2) The Collections object exists on both server and client.  Its purpose is only to simplify the number of new Meteor.collection calls we kept having to make.

3) We don't check for permission anywhere.  This is done automatically by Meteor when they implemented the Collections functions.
