### ISSUE TITLE
[FEATURE] LabVM Creation post to ETCD

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#30]
First, we need to make sure that Aaron is passing you the appropriate ETCD Authentication details, and that you are using them (if they exist) in connecting to ETCD.

Second, when the "magic method" is called and the LabVM is created, we need to use node-etcd to create two different records in etcd:

### DNS Record
This record points the SSH address (username.cmu.tuxlab.org) to the IP Address of the Docker Host containing the LabVM environment. This should be a simple A record in the [format of HelixDNS](https://github.com/mrwilson/helixdns).

### Proxy Record
The proxy record creates a pipe between an incoming WebSSH or SSH request and the destination VM.  You need to create records which are formatted to the standard of RedRouter, which is a key at `SSH::username` with just the docker-container and allowed-auth-methods fields set.

**Comment by DerekTBrown** [comment]
This is currently blocked by development on the Docker Middleware component:
https://github.com/learnlinux/tuxlab-infra/issues/17

**Comment by cemersoz** [comment]
this is implemented on my part, I push labVm info to etcd in env.js, using node-etcd. Just need you to have a working environment with etcd and pass me the info.
Also we should come up with a schema to store info in etcd.
And you should also make calls as to when I should remove the info, if I should

**Comment by DerekTBrown** [comment]
1) ETCD is currently working in the Vagrant environment.
2) We have two well documented schemas for ETCD- one for HelixDNS, one for RedRouter which are specified in their respective repositories.
3) You should simply create a `delete(userid)` method which is called when a student completes or close a lab
**4) How are you importing etcd authentication settings?**

**Comment by DerekTBrown** [comment]
Blocked by Aaron passing ETCD Authentication details (https://github.com/learnlinux/tuxlab-infra/issues/14)

**Comment by DerekTBrown** [comment]
@cemersoz 
- [ ] Test locally using (https://github.com/coreos/etcd/releases/download/v2.3.7/etcd-v2.3.7-linux-amd64.tar.gz) run `./etcd`, settings will be 127.0.0.1:2379, no authentication.
- [ ] Create a JSON object from nconf which stores the authentication data and is passed into node-etcd.
- [ ] Once Aaron has the Ansible code written, test in Vagrant (down cycles)

**Comment by DerekTBrown** [comment]
@cemersoz I finished the RedRouter docker component- so it is completely ready for you to test in Vagrant.

**Comment by cemersoz** [comment]
@DerekTBrown you realize nothing works on my computer yes? How can I test it otherwise? The implementation is complete and I really feel like it should work. Can I just trust that feeling?

**Comment by cemersoz** [comment]
@DerekTBrown I implemented everything and tested on vagrant environment. Good to go. Can set, get and delete any key.

**Comment by cemersoz** [comment]
I think you can close the issue?

**Comment by DerekTBrown** [comment]
**For Helix DNS:**

KEY: /helix/org/tuxlab/cmu/cemersoz/A 
VALUE: <IP ADDRESS OF HOST>

**For Redrouter**
KEY: /redrouter/SSH::cemersoz
VALUE:  
{ docker_container: <CONTAINERID>
   username: root
   allowed_auth: ["password"]
}

**Comment by DerekTBrown** [comment]
Fixed.
