### ISSUE TITLE
[FEATURE] LabFile Data Storage API

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#39]
We need to implement a Javascript function as part of the TuxLab object used in labfiles which enables instructors to write to a specific users' course record in a safe manner, as specified in the schema:

https://github.com/learnlinux/tuxlab-app/blob/master/docs/db_schema.md

**Comment by cemersoz** [comment]
@DerekTBrown did I not just do this?
setLabData, getLabDat etc

**Comment by DerekTBrown** [comment]
Indeed you did
