### ISSUE TITLE
[FEATURE] Loading Screen

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#41]
When the user selects a lab, we need to display an interim loading screen so we can prevent any errors that the Markdown View / Terminal View would have otherwise.

**Comment by cemersoz** [comment]
my methods accept callbacks to be called after everything on my end is done

**Comment by DerekTBrown** [comment]
I know... you are working on the loading screen which uses these callbacks.

**Comment by DerekTBrown** [comment]
Fixed in https://github.com/learnlinux/tuxlab-app/commit/73b6dcd7c3c06adfbddb69ebf1821db64bc4fce6
