### ISSUE TITLE
[REFACTOR] Instructor Views

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#44]
Instructor views are not separate:
https://github.com/learnlinux/tuxlab-app/tree/master/client/imports/ui/pages/instructor

Rather, instructor views are handled in the same components as the regular user views, but will simply have a check to determine if the current user is an instructor.

With this in mind, we need to create one more static views  for:

- [ ] Users (so the instructor can see which users are in his class and choose one)
- [ ] LabFile processing (discuss with @cemersoz )

and also update the existing views to include custom content for instructors:

- [ ] Dashboard
- [ ] Grade (Edit)

**Comment by sandershihacker** [comment]
Why is this closed?
