### ISSUE TITLE
[FEATURE] Publish/Subscribe in LabView

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#51]
We need to begin creating data bindings for the LabView (which would be the split view between the documentation and the terminal).  @sandershihacker  already has a template in place. @cemersoz I want you to begin by publishing the following data to the user:

- [x] SSH Password and Hostname
- [ ] List of Tasks and Task Status
- [x] Markdown for a given task
- [x] Button which calls the verifier method
- [x] Initialize Terminal View using Password and Hostname (https://github.com/learnlinux/tuxlab-app/issues/32)

**Comment by DerekTBrown** [comment]
@sandershihacker - You mentioned that you got client-size markdown rendering working.  Have you switched all of our code/dependencies over to this already?

**Comment by DerekTBrown** [comment]
Also are going to need to use a Loading Animation for the Terminal view while the instance is loading:

**Comment by DerekTBrown** [comment]
The Wetty view is complete.  You will just need to do dynamic data binding to the appropriate properties to bring it up:

https://www.sitepoint.com/angular-2-components-inputs-outputs/

**Comment by cemersoz** [comment]
@DerekTBrown I have no idea how I can get access to any of the things you mention

**Comment by DerekTBrown** [comment]
1) Hostname is just <username>@cmu.tuxlab.org
2) Password can be found by running docker exec cat /password
3) Markdown comes from the labs database.
4) Button was already created by sander.  You just need to function bind to it
5) When you get the rest done we can discuss terminal view.

**Comment by DerekTBrown** [comment]
https://github.com/learnlinux/tuxlab-app/commit/ad5d9e6b805d8920d92fe874c4e17a9f00c42315
