### ISSUE TITLE
[REFACTOR] Make ETCD Record Destruction Idempotent/Stateless

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#59]
This needs to function is one and/or both of the records exist:

https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/env.js#L68

**Comment by DerekTBrown** [comment]
@cemersoz -

1) You cannot just reject the promise with a Dockerode error.  You need to handle it internally, and pass back an opaque error to the user.
2) Use async

**Comment by cemersoz** [comment]
done except async
what do you mean by use async?

**Comment by DerekTBrown** [comment]
It is a programming tool at your disposal (https://github.com/caolan/async)- it implements a lot of your favorite functional programming methods in NodeJS, which will boost performance.
