### ISSUE TITLE
[REFACTOR] Template Fixes

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#64]
As we approach a finished product, I want to begin making some tweaks to the template:

- [x] **GLOBAL - Fix Scrolling Issue**
A) When the page is minimized below 1260px, a horizontal scrollbox appears at the bottom of the router.  This needs to be disabled.  Try minimizing the width of the explore page for example.

- [x] **Topbar**
A) Logo link is broken on some pages.

- [x] **Sidebar**
A) Update the sidebar menu to contain
    - Announcements
    - Terminal (which changes styling to show what lab is currently in progress)
    - Settings (goes to Account page)
    - Logout
This is ultimately only going to be used on the mobile view, and is a fill in for the dropdown component.

- [x] **Dashboard**
A) Title fonts need to be made smaller
    
- [x] **Explore Page**
A) Implement css animations for the content inside of the tabs so that they look cleaner when switched.  This may or may not be blocked by the Angular 2 Material Team (see Demo in Angular 1)[https://material.angularjs.org/latest/demo/tabs]
B) the title font for the name of the course is too large.  Decrease the size.
C) The annoying right chevron is still there in the search bar.  Can you move the search icon to where the chevron is, and put a compass icon where the search icon is?
D) The icons in the search bar have more padding on bottom than on top (which is clearly visible when you hover over one).  This needs to be adjusted using line-height, not the janky margin-top method you use.

- [x] **Search Page**
A) Remove the option to change how many courses are displayed.  Just set it to always be 15.
B) Add an "Instructor Name" Field to the Table
C) Remove the "Seats Left" view from the Table.
D) Add Icons to the next and previous page buttons
E) Reconfigure the page buttons to be like:
      < PREV          1-12 of 250             NEXT>

- [x] **Footer**
A) Footer links should be made into Material Buttons with proper hover effects

**Comment by sandershihacker** [comment]
Topbar done.

**Comment by sandershihacker** [comment]
Dashboard done, Sidebar done.

**Comment by sandershihacker** [comment]
Search page done.

**Comment by sandershihacker** [comment]
Footer done.

**Comment by sandershihacker** [comment]
Scrolling issue is due to the fixed width of the topbar, will be fixed when the topbar is responsive.

**Comment by sandershihacker** [comment]
Scrolling issue fix: overflow-x: hidden.
There will be no horizontal scrolling, but part of the toolbar is neither visible nor accessible.

**Comment by sandershihacker** [comment]
Animations for Angular 2 Material tab content are blocked.

**Comment by sandershihacker** [comment]
Explore page done.

**Comment by DerekTBrown** [comment]
BEAUTIFUL @sandershihacker !!
