### ISSUE TITLE
[FEATURE] LabFile Verification

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#77]
@cemersoz - I need you to fill in the code allowing the server to verify an incoming LabFile:

https://github.com/learnlinux/tuxlab-app/blob/master/collections/labs.ts#L72

After this is completed, retag this issue as for Alpha.2, because we need to implement the LabFile upload. I would be sure to use the CollectionsFS API for fileDrop functionality (it is much easier):

https://www.angular-meteor.com/tutorials/socially/angular2/handling-files-with-collectionfs

**Comment by DerekTBrown** [comment]
So, it turns out we can't use the same function to handle both insertion and update:

https://github.com/matb33/meteor-collection-hooks#beforeupdateuserid-doc-fieldnames-modifier-options

**Comment by DerekTBrown** [comment]
https://github.com/learnlinux/tuxlab-app/issues/72

**Comment by DerekTBrown** [comment]
After you are completed- please insert a statement in the test to verify this actually works:
https://github.com/learnlinux/tuxlab-app/blob/master/tests/tuxlab.db.js#L105

**Comment by cemersoz** [comment]
@DerekTBrown `return false;` in labValidator does not result in the expected behavior. It times out instead of aborting.

**Comment by cemersoz** [comment]
also there's a bug in typescript I think that gives us an unnecessary warning
https://github.com/angular/zone.js/issues/297
It was apparently solved 3 days ago, we can update

**Comment by DerekTBrown** [comment]
@cemersoz copy and paste the error?

**Comment by cemersoz** [comment]
1) Example Database should have example lab:
     Error: timeout of 10000ms exceeded
    at [object Object].<anonymous> (/home/cem/Documents/cem-tux/alph/node_modules/mocha/lib/runnable.js:158:19)
    at Timer.listOnTimeout (timers.js:92:15)


This is the error when labValidator returns false, either with a check failure or when I just replace the whole method body w `return false`

Other than that I have validation working

**Comment by DerekTBrown** [comment]
In retrospect, I think there is a better way to implement the LabValidator than as an action hook.   The action hook library (https://github.com/matb33/meteor-collection-hooks#additional-notes) says that returning false will stop the underlying method from running.  What this likely means is that the user can insert the data into their local database, and then the error comes when this data is synced with the server database.  In any case, what we are doing is not ideal.

I think a better way to do this would be to write a custom validator in the schema (whttps://github.com/aldeed/meteor-simple-schema#asynchronous-custom-validation-on-the-client).  This is pretty much the same thing I was doing before, except it would execute the check on both server and client code.
