### ISSUE TITLE
[REFACTOR] lab.env.js

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#84]
- [x] Remove [references to swarmerode](https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/lab.exec.js#L2)
- [x] [Rename methods to something meaningful.](https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/lab.env.js#L226)
- [x] [Get ETCD and Docker settings from nconf](https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/lab.env.js#L19)
- [x] [Make default image a setting in nconf](https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/lab.env.js#L118)
- [x] [Fix error handling](https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/lab.env.js#L358).  This is not proper- errors should be passed back as they are received, and not set equal to a string.

**Comment by cemersoz** [comment]
the only place where an error is assigned to a string is where I am reading the stdErr of a docker container? Otherwise I'm handling errors by logging them to TuxLog and rejecting with ("Internal error")

**Comment by cemersoz** [comment]
Done with this, will submit pull request
