### ISSUE TITLE
[FEATURE] Caching Labfiles

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#87]
In order to preserve memory, we should only have one copy of a given lab object open at a time.  Instead of evaling every time a user loads a lab, you should check to see if that lab is already in the cache, and use that copy if possible.

**Comment by DerekTBrown** [comment]
Please also be sure to respect versioning.  If the instructor changes the lab- then we need to alter the cache.

**Comment by cemersoz** [comment]
I have no idea how to do this. Is there a cache in mongo/meteor? what to do. Besides, we create specific lab objects for each student. I don't see how we could do this

**Comment by DerekTBrown** [comment]
Create an array which is indexed by lab name.  Every time a user opens a lab it checks to see if arr["labname"] is defined, if it is, just use that object, if not, load the labfile into the array.

**Comment by DerekTBrown** [comment]
Added in https://github.com/learnlinux/tuxlab-app/commit/1c70099479bc9ba13c3912ec3008775c9775b7d5
