### ISSUE TITLE
[REFACTOR] Remove Duplicate Underscore

### ISSUE THREAD

**Issue by DerekTBrown** [learnlinux/tuxlab-app#99]
We already have Underscore by virtue of Meteor.  There is no need to reimport it.  Plus, the point of underscore is to use underscores:

_.unzip([]) not underscore.unizip([])

https://github.com/learnlinux/tuxlab-app/blob/master/server/imports/api/lab.env.js

**Comment by cemersoz** [comment]
fixed this. Will be part of the next pull request
